# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mesh.proto import mesh_pb2 as mesh__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mesh_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DriverStub:
    """Agent connects to Driver on this service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/mesh.Driver/RegisterNode',
                request_serializer=mesh__pb2.RegisterRequest.SerializeToString,
                response_deserializer=mesh__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/mesh.Driver/Heartbeat',
                request_serializer=mesh__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=mesh__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.ReportResources = channel.unary_unary(
                '/mesh.Driver/ReportResources',
                request_serializer=mesh__pb2.ResourceReport.SerializeToString,
                response_deserializer=mesh__pb2.Ack.FromString,
                _registered_method=True)
        self.PreemptionWarning = channel.unary_unary(
                '/mesh.Driver/PreemptionWarning',
                request_serializer=mesh__pb2.PreemptionRequest.SerializeToString,
                response_deserializer=mesh__pb2.Ack.FromString,
                _registered_method=True)
        self.TaskProgress = channel.unary_unary(
                '/mesh.Driver/TaskProgress',
                request_serializer=mesh__pb2.TaskProgressReport.SerializeToString,
                response_deserializer=mesh__pb2.Ack.FromString,
                _registered_method=True)
        self.TaskComplete = channel.unary_unary(
                '/mesh.Driver/TaskComplete',
                request_serializer=mesh__pb2.TaskCompleteReport.SerializeToString,
                response_deserializer=mesh__pb2.Ack.FromString,
                _registered_method=True)


class DriverServicer:
    """Agent connects to Driver on this service.
    """

    def RegisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportResources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreemptionWarning(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=mesh__pb2.RegisterRequest.FromString,
                    response_serializer=mesh__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=mesh__pb2.HeartbeatRequest.FromString,
                    response_serializer=mesh__pb2.HeartbeatResponse.SerializeToString,
            ),
            'ReportResources': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportResources,
                    request_deserializer=mesh__pb2.ResourceReport.FromString,
                    response_serializer=mesh__pb2.Ack.SerializeToString,
            ),
            'PreemptionWarning': grpc.unary_unary_rpc_method_handler(
                    servicer.PreemptionWarning,
                    request_deserializer=mesh__pb2.PreemptionRequest.FromString,
                    response_serializer=mesh__pb2.Ack.SerializeToString,
            ),
            'TaskProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.TaskProgress,
                    request_deserializer=mesh__pb2.TaskProgressReport.FromString,
                    response_serializer=mesh__pb2.Ack.SerializeToString,
            ),
            'TaskComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.TaskComplete,
                    request_deserializer=mesh__pb2.TaskCompleteReport.FromString,
                    response_serializer=mesh__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mesh.Driver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mesh.Driver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Driver:
    """Agent connects to Driver on this service.
    """

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.Driver/RegisterNode',
            mesh__pb2.RegisterRequest.SerializeToString,
            mesh__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.Driver/Heartbeat',
            mesh__pb2.HeartbeatRequest.SerializeToString,
            mesh__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.Driver/ReportResources',
            mesh__pb2.ResourceReport.SerializeToString,
            mesh__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreemptionWarning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.Driver/PreemptionWarning',
            mesh__pb2.PreemptionRequest.SerializeToString,
            mesh__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TaskProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.Driver/TaskProgress',
            mesh__pb2.TaskProgressReport.SerializeToString,
            mesh__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TaskComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.Driver/TaskComplete',
            mesh__pb2.TaskCompleteReport.SerializeToString,
            mesh__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AgentStub:
    """Driver calls back to each Agent on this service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AssignTask = channel.unary_unary(
                '/mesh.Agent/AssignTask',
                request_serializer=mesh__pb2.TaskAssignment.SerializeToString,
                response_deserializer=mesh__pb2.Ack.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/mesh.Agent/CancelTask',
                request_serializer=mesh__pb2.TaskCancelRequest.SerializeToString,
                response_deserializer=mesh__pb2.Ack.FromString,
                _registered_method=True)
        self.PauseTask = channel.unary_unary(
                '/mesh.Agent/PauseTask',
                request_serializer=mesh__pb2.TaskPauseRequest.SerializeToString,
                response_deserializer=mesh__pb2.Ack.FromString,
                _registered_method=True)
        self.InstallLibrary = channel.unary_unary(
                '/mesh.Agent/InstallLibrary',
                request_serializer=mesh__pb2.LibraryInstallRequest.SerializeToString,
                response_deserializer=mesh__pb2.Ack.FromString,
                _registered_method=True)


class AgentServicer:
    """Driver calls back to each Agent on this service.
    """

    def AssignTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstallLibrary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AssignTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignTask,
                    request_deserializer=mesh__pb2.TaskAssignment.FromString,
                    response_serializer=mesh__pb2.Ack.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=mesh__pb2.TaskCancelRequest.FromString,
                    response_serializer=mesh__pb2.Ack.SerializeToString,
            ),
            'PauseTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseTask,
                    request_deserializer=mesh__pb2.TaskPauseRequest.FromString,
                    response_serializer=mesh__pb2.Ack.SerializeToString,
            ),
            'InstallLibrary': grpc.unary_unary_rpc_method_handler(
                    servicer.InstallLibrary,
                    request_deserializer=mesh__pb2.LibraryInstallRequest.FromString,
                    response_serializer=mesh__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mesh.Agent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mesh.Agent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Agent:
    """Driver calls back to each Agent on this service.
    """

    @staticmethod
    def AssignTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.Agent/AssignTask',
            mesh__pb2.TaskAssignment.SerializeToString,
            mesh__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.Agent/CancelTask',
            mesh__pb2.TaskCancelRequest.SerializeToString,
            mesh__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.Agent/PauseTask',
            mesh__pb2.TaskPauseRequest.SerializeToString,
            mesh__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InstallLibrary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.Agent/InstallLibrary',
            mesh__pb2.LibraryInstallRequest.SerializeToString,
            mesh__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
