"""Durable state storage for jobs, tasks, nodes, and checkpoints."""

from __future__ import annotations

from typing import Optional, Protocol

from mesh.models.job import Job
from mesh.models.node import Node
from mesh.models.task import TaskSpec
from mesh.recovery.checkpoint import Checkpoint


class StateStore(Protocol):
    def save_job(self, job: Job) -> None: ...
    def load_job(self, job_id: str) -> Optional[Job]: ...
    def list_jobs(self) -> list[Job]: ...

    def save_task(self, task: TaskSpec) -> None: ...
    def load_task(self, task_id: str) -> Optional[TaskSpec]: ...
    def list_tasks(self) -> list[TaskSpec]: ...

    def save_checkpoint(self, cp: Checkpoint) -> None: ...
    def load_checkpoint(self, task_id: str) -> Optional[Checkpoint]: ...

    def save_node(self, node: Node) -> None: ...
    def load_node(self, node_id: str) -> Optional[Node]: ...
    def list_nodes(self) -> list[Node]: ...

    def try_acquire_leadership(self, driver_id: str, term: int, ttl_seconds: float) -> bool: ...
    def renew_leadership(self, driver_id: str, term: int, ttl_seconds: float) -> bool: ...
    def get_leader(self) -> Optional[tuple[str, int]]: ...
